// <auto-generated />
using System;
using GymManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagementSystem.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305202805_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagementSystem.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("StaffAndMembers", (string)null);

                    b.HasDiscriminator<string>("Role").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GymManagementSystem.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("Date");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("Date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Plans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("GymManagementSystem.Models.Admin", b =>
                {
                    b.HasBaseType("GymManagementSystem.Models.Person");

                    b.Property<string>("Shifts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Age = 32,
                            Email = "admin@gym.com",
                            FullName = "Sayed Ahmed",
                            Gender = "Male",
                            Password = "$2a$11$WXHKRbxbTYUP8.EDYMqs8ej/E1/3oEurvQMl2O2tCbXTd/.PYmn4G",
                            Phone = "01099999999",
                            Shifts = "Morning"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Age = 26,
                            Email = "support@gym.com",
                            FullName = "Nour El-Sayed",
                            Gender = "Female",
                            Password = "$2a$11$BGh.QBPmTb2/ag0t10C2Z.e86xsq5hBZQVOcXHb6vzAoXUMNtlea6",
                            Phone = "01188888888",
                            Shifts = "Evening"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Coach", b =>
                {
                    b.HasBaseType("GymManagementSystem.Models.Person");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Coach");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Age = 35,
                            Email = "ahmed.ali@gym.com",
                            FullName = "Ahmed Ali",
                            Gender = "Male",
                            Password = "$2a$11$MSGydp8Ry8O2TB.ucwg3I.XpUvqjt1J8fjPkXJrOmxeW7uItZHKxe",
                            Phone = "01000000000",
                            ExperienceYears = 6
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Age = 30,
                            Email = "sara.mohamed@gym.com",
                            FullName = "Sara Mohamed",
                            Gender = "Female",
                            Password = "$2a$11$MA/THxwDyYVgaDrqqhUAzuhoeNlVyaiEE0mUuWW71Y1ZLuRR7Ltvq",
                            Phone = "01111111111",
                            ExperienceYears = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Age = 40,
                            Email = "omar.hassan@gym.com",
                            FullName = "Omar Hassan",
                            Gender = "Male",
                            Password = "$2a$11$O5iOsLS9ZaSE9nwSC8tNz.V1qaQRn3hzbyuKFwW/ywgTBr5M8h5Sq",
                            Phone = "01222222222",
                            ExperienceYears = 7
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Models.Member", b =>
                {
                    b.HasBaseType("GymManagementSystem.Models.Person");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("Bit");

                    b.Property<int>("SessionsAvailable")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("CoachId");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Subscription", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Member", "Member")
                        .WithOne("Subscription")
                        .HasForeignKey("GymManagementSystem.Models.Subscription", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Member", b =>
                {
                    b.HasOne("GymManagementSystem.Models.Coach", "Coach")
                        .WithMany("Members")
                        .HasForeignKey("CoachId");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Coach", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GymManagementSystem.Models.Member", b =>
                {
                    b.Navigation("Subscription")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
